### ISSUE TITLE
Regarding AOP and concurrent rest calls 

### ISSUE THREAD

**Issue by mEEt126** [niket17590/java-springboot-tutorials#2]
Just for understanding, Can you explain how it will handle concurrent rest calls. Whether it will block concurrent REST calls or how it will handle it. 
Thank you.

**Comment by niket17590** [comment]
AOP is specifically used for cross-cutting concerns. Obviously, the call is synchronous for any AOP call (whether it is a rest call or an internal object-to-object call), but the impact is minimal.

A lot depends on what you are doing within your aspect logic. It is advised to do very light-weight operations (e.g. logging, emails, notifications, alerts, etc.) 

You can get your answer by putting a debug pointer in your AOP aspect method. Then make two REST calls, which will work on two separate threads, and both threads will remain blocked until you release your debug pointer in code. It will help you understand how AOP works.
